app = 'hone-api'
primary_region = 'sjc'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '8080'
  UPLOADS_DIR = '/data/uploads'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = 'hone_uploads'
  destination = '/data/uploads'
